#!/bin/sh

BINARY_DIR="$HOME/bin"
PREFIX_DIR="$HOME/usr/local"
SUPPORTS=("emacs" "vim")
TARGET=$1

function usage() {
    cat <<EOS
Usage:
 $ $0 target [version]
EOS
}

function setup() {
    if [ ! -d $BINARY_DIR ]
    then
        mkdir $BINARY_DIR
    fi

    if [ ! -d $PREFIX_DIR ]
    then
        mkdir -p $PREFIX_DIR
    fi
}

function emacs() {
    LATEST_VERSION="24.5"
    CONTENT="emacs-${LATEST_VERSION}"
    ARCH_FILE="${CONTENT}.tar.gz"
    MIRROR_LIST_URL="http://ftpmirror.gnu.org/emacs"
    FLAGS="--without-x"

    setup

    TMP_DIR=$(mktemp -d)
    wget "${MIRROR_LIST_URL}/${ARCH_FILE}" -O "${TMP_DIR}/${ARCH_FILE}"
    tar zxf $TMP_DIR/$ARCH_FILE -C $TMP_DIR
    cd $TMP_DIR/$CONTENT

    ./configure --prefix=$PREFIX_DIR/$CONTENT $FLAGS
    make
    make install

    
    if [ -f $BINARY_DIR/emacs ]
    then
        mv $BINARY_DIR/emacs $BINARY_DIR/emacs.org
    fi
    ln -s $PREFIX_DIR/$CONTENT/bin/emacs $BINARY_DIR/emacs
}

function vim() {
    setup
    echo "Write an vim install script here"
}

if [ "$TARGET" == "" ]
then
    usage
    exit 0
fi

case $TARGET in
    emacs)
        emacs
        ;;
    vim)
        vim
        ;;
    *)
        echo "[Error] Not support $TARGET"
        echo "  Support: "
        for s in "${SUPPORTS[@]}"
        do
            echo "    $s"
        done
        ;;
esac
